In [5]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서','radio']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('Label encoding result:',labels)

# 영어 먼저 , 가나다 순으로 순서대로 출력

Label encoding result: [0 2 5 6 4 4 3 3 1]


In [6]:
print('Encoding classes:',encoder.classes_)

Encoding classes: ['TV' 'radio' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [13]:
print('Decoding values:',encoder.inverse_transform([4,5,2,0,1,1,3,3,6,1]))

Decoding values: ['선풍기' '전자렌지' '냉장고' 'TV' 'radio' 'radio' '믹서' '믹서' '컴퓨터' 'radio']


In [25]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
# print(labels)
labels=labels.reshape(-1,1)
# print(labels.shape)
one_hot_encoder= OneHotEncoder()
one_hot_encoder.fit(labels)
one_hot_labels= one_hot_encoder.transform(labels)

print('One-Hot Encoder Data')
print(one_hot_labels.toarray())  # 알아볼수있도록 리스트 형태로 보이게 toarray씀 -->싸이파이 에서 나온것 
print('Dimension of Encoding Data')
print(one_hot_labels.shape)

       

One-Hot Encoder Data
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
Dimension of Encoding Data
(8, 6)


C:\Users\dkfka\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [19]:
import pandas as pd

df= pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

#one_hot_encoding으로 출력됨   -- 자신의 포지션에만 1이 출력됨  나머진 다 0

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

In [20]:
#######scaling  표준화/정규화 

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data=iris.data
df_iris=pd.DataFrame(data=iris_data,columns=iris.feature_names)

print('Average')
print(df_iris.mean())
print('\nVariance')
print(df_iris.var())

Average
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Variance
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df_iris)
scaled_iris = scaler.transform(df_iris)

df_scaled_iris=pd.DataFrame(data=scaled_iris, columns=iris.feature_names)

print('Average')
print(df_scaled_iris.mean())
print('\nVariance')
print(df_scaled_iris.var())    # 평균(u)는 거의 0에 수렴, 분산은 거의 1에 수렴!! 표준화의 정의 처럼!

Average
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

Variance
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [32]:
### 0~1 정규화 min-max

from sklearn.preprocessing import MinMaxScaler

scaler =MinMaxScaler()
scaler.fit(df_iris)
scaled_iris = scaler.transform(df_iris)

df_scaled_iris= pd.DataFrame(data=scaled_iris, columns= iris.feature_names)

print('Min value')
print(df_scaled_iris.min())
print("\nMax value")
print(df_scaled_iris.max())
print('\nVariance')
print(df_scaled_iris.var())

Min value
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

Max value
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

Variance
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64
