In [2]:
# 1 
import numpy as np

a = np.arange(2,11,1)
print(a)

[ 2  3  4  5  6  7  8  9 10]


In [24]:
#해답
a = np.arange(2,11,1).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
a.shape=(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [7]:
#2
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
b[6]=11   # index로 접근함!
print(b)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [32]:
#3
c = [1,2,0,0,4,0]
print(c)

for i in c:
    if i !=0:
        print([i])  
        
        #lamba, map 함수 로 할수있다--> 구글링 하기 

[1, 2, 0, 0, 4, 0]
[1]
[2]
[4]


In [29]:
# import numpy as np
e = np,array([1,2,0,0,4,0])
for val in e :
    if val > 0 :
        tmp= no.append(tmp,[val])

TypeError: 'module' object is not callable

In [33]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [41]:
dt_clf = DecisionTreeClassifier()
train_data= iris.data
print(train_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [42]:
train_label = iris.target
print(train_label)
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [43]:
train_label = iris.target
dt_clf.fit(train_data, train_label)

pred = dt_clf.predict(train_data)
print("prediction accuracy:", accuracy_score(train_label,pred))

prediction accuracy: 1.0


In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold=KFold(n_splits=3)
cv_accuracy=[]
print('iris Data Set Size:', features.shape[0])
 
fold_index=0
for train_index, test_index, in kfold.split(features):
    x_train, x_test  = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    
#     print(train_index)
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    fold_index+=1
    
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} fold accuracy:{1}, train size:{2}, val size:{3}'.format(fold_index, accuracy, train_size, test_size))
    print('\n#{0} val index:{1}'.format(fold_index,test_index))
    
    cv_accuracy.append(accuracy)
print('\n## avg val accuracy:', np.mean(cv_accuracy))

iris Data Set Size: 150

#1 fold accuracy:0.0, train size:100, val size:50

#1 val index:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

#2 fold accuracy:0.0, train size:100, val size:50

#2 val index:[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]

#3 fold accuracy:0.0, train size:100, val size:50

#3 val index:[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## avg val accuracy: 0.0


In [ ]:
#iloc --> 인댁스로 값을 뽑아 올때!

In [58]:
import pandas as pd
iris = load_iris()

df_iris=pd.DataFrame(data=iris.data, columns =iris.feature_names)
df_iris['label']=iris.target
df_iris['label'].value_counts()

kfold= KFold(n_splits=3)

for train_index, test_index in kfold.split(df_iris):
    fold_index+=1
    
    label_train= df_iris['label'].iloc[train_index]
    label_test =df_iris['label'].iloc[test_index]
    print('##Cross validation:{0}'.format(fold_index))
    print('Train label distribution:\n', label_train.value_counts())
    print('Val label distribution:\n', label_test.value_counts())

##Cross validation:15
Train label distribution:
 2    50
1    50
Name: label, dtype: int64
Val label distribution:
 0    50
Name: label, dtype: int64
##Cross validation:16
Train label distribution:
 2    50
0    50
Name: label, dtype: int64
Val label distribution:
 1    50
Name: label, dtype: int64
##Cross validation:17
Train label distribution:
 1    50
0    50
Name: label, dtype: int64
Val label distribution:
 2    50
Name: label, dtype: int64


In [61]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
fold_index = 0

for train_index, test_index in skf.split(df_iris,df_iris['label']):
    fold_index+=1
    
    label_train=df_iris['label'].iloc[train_index]
    label_test=df_iris['label'].iloc[test_index]
    
    print('##Cross validation:{0}'.format(fold_index))
    print('Train label distribution:\n',label_train.value_counts())
    print('Val label distribution:\n',label_test.value_counts())    

# 동일한 데이터 분포 셋을 얻기 위해 !! TRAIN DATA/ TEST DATA 각각 비율대로 뽑기 위해서!!

##Cross validation:1
Train label distribution:
 2    33
1    33
0    33
Name: label, dtype: int64
Val label distribution:
 2    17
1    17
0    17
Name: label, dtype: int64
##Cross validation:2
Train label distribution:
 2    33
1    33
0    33
Name: label, dtype: int64
Val label distribution:
 2    17
1    17
0    17
Name: label, dtype: int64
##Cross validation:3
Train label distribution:
 2    34
1    34
0    34
Name: label, dtype: int64
Val label distribution:
 2    16
1    16
0    16
Name: label, dtype: int64


In [69]:
#original set중에 --> training set 만 돌리는 중!! testing은 신경쓰지 말기! 여기서 test_data랑은 상관 없는것 
# 여기서 test_data는 validation이다!!! validation 50개이다!!

from sklearn.model_selection import StratifiedKFold

iris=load_iris()
features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=156)

skfold =StratifiedKFold(n_splits=3)
fold_index =0
lst_accuracy=[]

for train_index, test_index in skfold.split(features,label):
    x_train, x_test = features[train_index],features[test_index]
    y_train, y_test = label[train_index],label[test_index]
    
    dt_clf.fit(x_train,y_train)
    pred=dt_clf.predict(x_test)
    
    fold_index+=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size=x_train.shape[0]
    test_size=x_test.shape[0]
    
    print('\n#{0}Cross val accuracy:{1}, train size:{2}, test size:{3}'.format(fold_index, accuracy,train_size,test_size))
    print('#{0} Val index:{1}'.format(fold_index,test_index))
    
    lst_accuracy.append(accuracy)
    
print('\n##fold val accuracy:', np.round(lst_accuracy,4))
print('##avg val accuracy:', np.mean(lst_accuracy))


#1Cross val accuracy:0.9804, train size:99, test size:51
#1 Val index:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116]

#2Cross val accuracy:0.9216, train size:99, test size:51
#2 Val index:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133]

#3Cross val accuracy:0.9792, train size:102, test size:48
#3 Val index:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

##fold val accuracy: [0.9804 0.9216 0.9792]
##avg val accuracy: 0.9604


In [78]:
#stratified 된 KFold 값을 출력해줌 ### cross_val_score( 예측 해주는 알고리즘 !! )

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

iris =load_iris()
dt_clf=DecisionTreeClassifier(random_state =156)    # 초기값을 난수로 생성  seed값 고정! 

data=iris.data
label=iris.target    # data는 data고 label은 target이고! 

scores= cross_val_score(dt_clf, data, label, scoring='accuracy',cv=3)
print("Fold val accuracy:" , np.round(scores,4))
print('Avg val accuracy:',np.round(np.mean(scores),4))


Fold val accuracy: [0.9804 0.9216 0.9792]
Avg val accuracy: 0.9604


In [80]:
# print(iris.data)    # features
print(iris.target)   #  label 이라고 관용적으로 쓰는것! 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [81]:
#하이퍼 파라미터를 튜닝 --> 전처리 
# 최적의 성능  


3

In [83]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)
dtree= DecisionTreeClassifier()

parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

import pandas as pd
grid_dtree = GridSearchCV(dtree,param_grid=parameters, cv=3,refit=True)

grid_dtree.fit(x_train,y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [84]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(x_test)
print('Test dataset accuracy:{0:.4f}'.format(accuracy_score(y_test,pred)))

Test dataset accuracy:0.9667
